### ISSUE TITLE
Certain tests fail on windows 

### ISSUE THREAD

**Issue by toothsy** [bebop/poly#301]
**Describe the bug**
Hello,I'm a windows user and I cloned the repo locally, installed all the vscode extensions, and ran all the tests, some test cases failed

**To Reproduce**
1. have a windows Operating system
2. clone the repo locally
3. run it in VSC
4. run all tests

**Expected behavior**
all tests must be green but some failed

**Screenshots**
![image](https://user-images.githubusercontent.com/48372345/227131575-65ac90ed-ea50-4084-a9fa-36d9822b4d16.png)

**Desktop:**
 - OS: [Windows]

**Additional context**
upon closer inspection in gff_test.go
- ![image](https://user-images.githubusercontent.com/48372345/227131786-4d4ba94a-4b08-4d10-8bce-502655e4e2fa.png)
     -  atoiFn is getting "6370\r" as its input hence it is panics
- the newline error due to windows is causing the issue

**Comment by carreter** [comment]
Once #340 is merged, this will be an easy fix.

**Comment by carreter** [comment]
Also @toothsy could you inspect the data being read in by the tests and let us know what the line endings are on Windows? You can do this using `git ls-files --eol`, please post the output of that here.

**Comment by carreter** [comment]
Bumping this. If anyone has access to a Windows machine, info would be greatly appreciated! Worst case I can spin up a VM, but I'm lazy...
